<a href="https://colab.research.google.com/github/ansaganakhat/project-1/blob/main/C%D3%A8%D0%964.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  NumPy және Машиналық Оқыту үшін Python Негіздері

**Тапсырма саны:** 10  

##  Нұсқаулық

Төмендегі 10 тапсырманың әрқайсысында `# КОДТЫ ОСЫНДА ЖАЗ` деген белгі бар. Сол жерге өз шешімінді жаз.


In [2]:
# Қажетті кітапханаларды импорттау
import numpy as np
import math

# I Бөлім: NumPy Кітапханасымен Жұмыс

**NumPy** (Numerical Python) сандық есептеулерге арналған Python кітапханасы. Ол көп өлшемді массивтермен (ndarray) жұмыс істеуге, математикалық операциялар жүргізуге және деректерді өңдеуге мүмкіндік береді. Машиналық оқытуда NumPy матрицалық есептеулер мен деректер алдын ала өңдеуінің негізі болып табылады.

> **Тапсырмалар 1–5:** NumPy массивтерін құру, индекстеу, операциялар және статистика.

## Тапсырма 1: NumPy Массивін Құру және Негізгі Сипаттамалар

**Мақсат:** NumPy массивін қолмен жасау және оның қасиеттерін зерттеу.

**Шарт:**

1. `[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]` мәндерінен тұратын NumPy массивін жаса.
2. Массивтің мынадай сипаттамаларын экранға шығар:
   - Өлшемі (`shape`)
   - Деректер типі (`dtype`)
   - Элементтер саны (`size`)
   - Өлшемдер саны (`ndim`)

**Күтілетін нәтиже үлгісі:**
```
Массив: [ 10  20  30  40  50  60  70  80  90 100]
Өлшемі: (10,)
Деректер типі: int64
Элементтер саны: 10
Өлшемдер саны: 1
```

In [3]:
# Тапсырма 1: NumPy массивін құру

# КОДТЫ ОСЫНДА ЖАЗ
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print("Массив:", arr)
print("Өлшемі (shape):", arr.shape)
print("Деректер типі (dtype):", arr.dtype)
print("Элементтер саны (size):", arr.size)
print("Өлшемдер саны (ndim):", arr.ndim)

Массив: [ 10  20  30  40  50  60  70  80  90 100]
Өлшемі (shape): (10,)
Деректер типі (dtype): int64
Элементтер саны (size): 10
Өлшемдер саны (ndim): 1


## Тапсырма 2: Матрица Құру және Матрицалық Операциялар

**Мақсат:** 2D массив (матрица) жасау және негізгі матрицалық операцияларды орындау.

NumPy-да матрицалар 2 өлшемді ndarray ретінде сақталады. Машиналық оқытуда деректер жиыны көбінесе (n_samples × n_features) пішіндегі матрица түрінде ұсынылады. Матрицалық операциялар линейлі регрессия, нейрондық желілер және басқа алгоритмдердің негізін қалайды.

**Шарт:**

1. Мынадай 3×3 матрицаны жаса:
```
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
```
2. Осы матрицаны **транспонирлей** (`.T`).
3. Матрицаны өзіне **матрицалық көбейт** (`np.dot` немесе `@`).
4. Нәтижелерді экранға шығар.

In [8]:
# Тапсырма 2: Матрица және матрицалық операциялар

# КОДТЫ ОСЫНДА ЖАЗ
ansa=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ansa)
print(ansa.T)
print(ansa@ansa)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


## Тапсырма 3: Индекстеу, Тілімдеу (Slicing) және Сүзгілеу

**Мақсат:** NumPy массивіндегі элементтерге индекс арқылы қол жеткізу және шарт бойынша сүзу.

NumPy-да Boolean маска — шартқа сай элементтерді таңдаудың тиімді тәсілі. Мысалы, деректерден аномалиялар немесе белгілі бір диапазондағы мәндерді жылдам алып тастауға болады. Бұл алдын ала өңдеу (preprocessing) кезеңінде жиі қолданылады.

**Шарт:**

1. 1-ден 20-ға дейінгі сандардан тұратын массив жаса (`np.arange`).
2. Массивтің **алғашқы 5** элементін шығар.
3. Массивтің **соңғы 5** элементін шығар.
4. Массивтің **жұп индекстегі** элементтерін шығар (0, 2, 4, ...).
5. Мәні **10-нан үлкен** элементтерді ғана шығар (Boolean индекстеу).

In [9]:
# Тапсырма 3: Индекстеу, тілімдеу және сүзгілеу

# КОДТЫ ОСЫНДА ЖАЗ
# 1) 1-ден 20-ға дейінгі массив
arr = np.arange(1, 21)

# 2) Алғашқы 5 элемент
print("Алғашқы 5:", arr[:5])

# 3) Соңғы 5 элемент
print("Соңғы 5:", arr[-5:])

# 4) Жұп индекстегі элементтер (0,2,4,...)
print("Жұп индекстер:", arr[::2])

# 5) 10-нан үлкен элементтер
print("10-нан үлкен:", arr[arr > 10])

Алғашқы 5: [1 2 3 4 5]
Соңғы 5: [16 17 18 19 20]
Жұп индекстер: [ 1  3  5  7  9 11 13 15 17 19]
10-нан үлкен: [11 12 13 14 15 16 17 18 19 20]


## Тапсырма 4: Статистикалық Функциялар

**Мақсат:** NumPy-дың кірістірілген статистикалық функцияларын пайдалану.

Деректерді зерттеудің (EDA) бірінші қадамы — негізгі статистикалық көрсеткіштерді есептеу. Орташа мән, медиана, стандартты ауытқу және персентильдер деректер таралуын түсінуге көмектеседі. NumPy бұл есептеулерді векторланған түрде өте жылдам орындайды.

**Шарт:**

`np.random.seed(42)` арқылы кездейсоқтықты бекіт, содан кейін 0-ден 100-ге дейінгі **50 кездейсоқ бүтін сан** жаса.

Келесі статистикалық көрсеткіштерді есепте және шығар:
- Минимум және максимум
- Орташа мән (mean)
- Медиана
- Стандартты ауытқу
- Дисперсия
- 25-ші және 75-ші персентильдер

In [10]:
# Тапсырма 4: Статистикалық функциялар
np.random.seed(42)  # Қайталануы үшін кездейсоқтықты бекіту

# КОДТЫ ОСЫНДА ЖАЗ
# Кездейсоқтықты бекіту
arr = np.random.randint(0, 101, 50)

print("Массив:", arr)

print("Минимум:", np.min(arr))
print("Максимум:", np.max(arr))

print("Орташа мән (mean):", np.mean(arr))
print("Медиана:", np.median(arr))

print("Стандартты ауытқу:", np.std(arr))
print("Дисперсия:", np.var(arr))

print("25-персентиль:", np.percentile(arr, 25))
print("75-персентиль:", np.percentile(arr, 75))

Массив: [ 51  92  14  71  60  20  82  86  74  74  87  99  23   2  21  52   1  87
  29  37   1  63  59  20  32  75  57  21  88  48  90  58  41  91  59  79
  14  61  61  46  61  50  54  63   2 100  50   6  20  72]
Минимум: 1
Максимум: 100
Орташа мән (mean): 52.08
Медиана: 57.5
Стандартты ауытқу: 28.62016072631319
Дисперсия: 819.1136
25-персентиль: 24.5
75-персентиль: 74.0


## Тапсырма 5: Пішінді Өзгерту (Reshape) және Хабарлау (Broadcasting)

**Мақсат:** Массив пішінін өзгерту және NumPy broadcasting механизмін түсіну.

Broadcasting  NumPy-дың әртүрлі пішіндегі массивтерге автоматты түрде арифметикалық операция қолдану мүмкіндігі. Reshape функциясы деректерді нейрондық желілерге немесе sklearn модельдеріне беру алдында жиі қолданылады.

**Шарт:**

1. 1-ден 12-ге дейінгі сандардан тұратын массив жаса (`np.arange`).
2. Оны **3×4 матрицаға** түрлендір (`reshape`).
3. Матрицаның **әр жолына** `[10, 20, 30, 40]` векторын қос (broadcasting).
4. Матрицаның **әр бағанын** `[[1], [2], [3]]` бағандық векторына көбейт (broadcasting).
5. Нәтижелерді шығар.

In [11]:
# Тапсырма 5: Reshape және Broadcasting

# КОДТЫ ОСЫНДА ЖАЗ
# 1) 1-ден 12-ге дейін массив
arr = np.arange(1, 13)

# 2) 3x4 матрицаға түрлендіру
matrix = arr.reshape(3, 4)
print("Бастапқы матрица:\n", matrix)

# 3) Әр жолға [10, 20, 30, 40] қосу
row_vector = np.array([10, 20, 30, 40])
result_add = matrix + row_vector
print("\nЖол векторын қосу:\n", result_add)

# 4) Әр бағанды [[1],[2],[3]] векторына көбейту
col_vector = np.array([[1], [2], [3]])
result_mul = matrix * col_vector
print("\nБаған векторымен көбейту:\n", result_mul)

Бастапқы матрица:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Жол векторын қосу:
 [[11 22 33 44]
 [15 26 37 48]
 [19 30 41 52]]

Баған векторымен көбейту:
 [[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]]


# II Бөлім: Машиналық Оқыту үшін Python Негіздері

Python-ның функциялары мен кластары машиналық оқыту жүйелерін модульдік және қайта пайдалануға болатын түрде құруға мүмкіндік береді. ML pipeline-дарын, деректерді өңдеу логикасын және модель архитектурасын таза кодпен ұйымдастыру үшін OOP принциптері өте маңызды. scikit-learn кітапханасының өзі де осындай кластық құрылымға негізделген.

> **Тапсырмалар 6–10:** Функциялар, декораторлар, кластар және ML компоненттерін модельдеу.

## Тапсырма 6: ML Алдын Ала Өңдеу Функциялары

**Мақсат:** Деректерді нормализациялайтын және стандарттайтын функциялар жазу.

Нормализация мен стандарттау — ML алгоритмдерінің дұрыс жұмыс істеуі үшін маңызды алдын ала өңдеу қадамдары. Min-Max нормализациясы мәндерді [0, 1] диапазонына, Z-score стандарттауы орташа мәнді 0, стандартты ауытқуды 1 етіп түрлендіреді. Бұл SVM, KNN, нейрондық желі сияқты алгоритмдер үшін өте маңызды.

**Шарт:**

Екі функция жаз:

**`min_max_normalize(arr)`** — Min-Max нормализациясы:
$$x_{norm} = \frac{x - x_{min}}{x_{max} - x_{min}}$$

**`z_score_standardize(arr)`** — Z-score стандарттауы:
$$x_{std} = \frac{x - \mu}{\sigma}$$

Екі функцияны да `[2, 4, 4, 4, 5, 5, 7, 9]` массивіне қолдан және нәтижені шығар.

In [12]:
# Тапсырма 6: Нормализация және стандарттау функциялары

# КОДТЫ ОСЫНДА ЖАЗ
def min_max_normalize(arr):
    arr = np.array(arr, dtype=float)
    xmin = np.min(arr)
    xmax = np.max(arr)
    return (arr - xmin) / (xmax - xmin)


def z_score_standardize(arr):
    arr = np.array(arr, dtype=float)
    mean = np.mean(arr)
    std = np.std(arr)
    return (arr - mean) / std



data = np.array([2, 4, 4, 4, 5, 5, 7, 9])

minmax_result = min_max_normalize(data)
zscore_result = z_score_standardize(data)

print("Бастапқы массив:", data)
print("Min-Max нормализация:", minmax_result)
print("Z-score стандарттау:", zscore_result)

Бастапқы массив: [2 4 4 4 5 5 7 9]
Min-Max нормализация: [0.         0.28571429 0.28571429 0.28571429 0.42857143 0.42857143
 0.71428571 1.        ]
Z-score стандарттау: [-1.5 -0.5 -0.5 -0.5  0.   0.   1.   2. ]


## Тапсырма 7: Рекурсия және Lambda Функциялар

**Мақсат:** Рекурсивті функция және lambda өрнектерін ML контекстінде қолдану.

Lambda функциялар — атаусыз шағын функциялар, ML-де деректерді трансформациялау үшін `map()`, `filter()`, `sorted()` функцияларымен жиі қолданылады. Рекурсия болса күрделі алгоритмдерді (мысалы, шешім ағашының тереңдігін есептеу) элегантты жазуға мүмкіндік береді.

**Шарт:**

1. **Рекурсивті функция:** `factorial(n)` — n! санын рекурсия арқылы есепте.
2. **Lambda:** `[0.1, 0.5, 0.9, 1.5, -0.3, 2.0]` тізімінен тек `[0, 1]` диапазонындағы мәндерді `filter` + `lambda` арқылы алып шығар.
3. **Lambda + map:** `[-2, -1, 0, 1, 2]` тізіміндегі әр элементке ReLU активация функциясын `map` + `lambda` арқылы қолдан.

> ReLU(x) = max(0, x)

In [13]:
# Тапсырма 7: Рекурсия және Lambda функциялар

# КОДТЫ ОСЫНДА ЖАЗ

def factorial(n):
    if n == 0 or n == 1:
        return 1
    return n * factorial(n - 1)

print("5! =", factorial(5))


data = [0.1, 0.5, 0.9, 1.5, -0.3, 2.0]

filtered = list(filter(lambda x: 0 <= x <= 1, data))

print("Диапазон [0,1] мәндері:", filtered)

numbers = [-2, -1, 0, 1, 2]

relu_result = list(map(lambda x: max(0, x), numbers))

print("ReLU нәтижесі:", relu_result)

5! = 120
Диапазон [0,1] мәндері: [0.1, 0.5, 0.9]
ReLU нәтижесі: [0, 0, 0, 1, 2]


## Тапсырма 8: Кластар — ML Метрикаларын Есептеуші

**Мақсат:** OOP принциптерін пайдаланып, классификация метрикаларын есептейтін класс жазу.

Машиналық оқытуда модель сапасын бағалау үшін Accuracy, Precision, Recall, F1-score метрикалары қолданылады. Оларды бір класс ішінде топтастыру кодтың модульдігін арттырады және sklearn-дің `classification_report` функциясына ұқсас нәтиже береді.

**Шарт:**

`ClassificationMetrics` атты класс жаз. Конструктор `y_true` (нақты мәндер) және `y_pred` (болжамдар) параметрлерін қабылдасын.

Класта мынадай әдістер болуы керек:
- `accuracy()` — дұрыс болжамдар үлесі
- `precision()` — дәлдік: TP / (TP + FP)
- `recall()` — толықтық: TP / (TP + FN)
- `f1_score()` — F1: 2 × (precision × recall) / (precision + recall)
- `report()` — барлық метрикаларды форматталған түрде шығарады

Тест деректері:
```python
y_true = [1, 0, 1, 1, 0, 1, 0, 0, 1, 0]
y_pred = [1, 0, 1, 0, 0, 1, 1, 0, 1, 0]
```

In [14]:
# Тапсырма 8: ClassificationMetrics класы

# Тест деректері
y_true = [1, 0, 1, 1, 0, 1, 0, 0, 1, 0]  # Нақты белгілер
y_pred = [1, 0, 1, 0, 0, 1, 1, 0, 1, 0]  # Болжамдар

# КОДТЫ ОСЫНДА ЖАЗ

class ClassificationMetrics:
    def __init__(self, y_true, y_pred):
        self.y_true = y_true
        self.y_pred = y_pred


    def accuracy(self):
        correct = sum(1 for yt, yp in zip(self.y_true, self.y_pred) if yt == yp)
        return correct / len(self.y_true)


    def precision(self):
        tp = sum(1 for yt, yp in zip(self.y_true, self.y_pred) if yt == 1 and yp == 1)
        fp = sum(1 for yt, yp in zip(self.y_true, self.y_pred) if yt == 0 and yp == 1)

        if tp + fp == 0:
            return 0
        return tp / (tp + fp)


    def recall(self):
        tp = sum(1 for yt, yp in zip(self.y_true, self.y_pred) if yt == 1 and yp == 1)
        fn = sum(1 for yt, yp in zip(self.y_true, self.y_pred) if yt == 1 and yp == 0)

        if tp + fn == 0:
            return 0
        return tp / (tp + fn)

    def f1_score(self):
        p = self.precision()
        r = self.recall()

        if p + r == 0:
            return 0
        return 2 * (p * r) / (p + r)


    def report(self):
        print("Classification Report")
        print("---------------------")
        print(f"Accuracy : {self.accuracy():.2f}")
        print(f"Precision: {self.precision():.2f}")
        print(f"Recall   : {self.recall():.2f}")
        print(f"F1-score : {self.f1_score():.2f}")


metrics = ClassificationMetrics(y_true, y_pred)


metrics.report()

Classification Report
---------------------
Accuracy : 0.80
Precision: 0.80
Recall   : 0.80
F1-score : 0.80


## Тапсырма 9: Мұрагерлік (Inheritance) — ML Модель Иерархиясы

**Мақсат:** Python-да кластар иерархиясын (мұрагерлік) пайдаланып ML модельдерін модельдеу.

Мұрагерлік (inheritance) — OOP-тың негізгі принципі. scikit-learn барлық модельдерін `BaseEstimator` базалық класынан туындатады, бұл `fit()`, `predict()`, `score()` сияқты ортақ интерфейсті қамтамасыз етеді. Осы паттернді түсіну ML кітапханаларының архитектурасын жобалауға негіз береді.

**Шарт:**

1. **`BaseModel`** — базалық класс:
   - `__init__(self, model_name)` — модель атын сақтайды
   - `fit(X, y)` — `NotImplementedError` шығарады (абстрактілі)
   - `predict(X)` — `NotImplementedError` шығарады (абстрактілі)
   - `describe()` — модель туралы ақпаратты шығарады

2. **`LinearRegressionModel(BaseModel)`** — туынды класс:
   - `fit(X, y)` — `np.linalg.lstsq` арқылы коэффициенттерді табады
   - `predict(X)` — `X @ weights` арқылы болжайды
   - `describe()` — базалық сипаттаманы + коэффициенттерді шығарады

3. Тест деректерінде `fit` → `predict` → `describe` тізбегін шақыр.

In [15]:
# Тапсырма 9: Мұрагерлік — ML Модель Иерархиясы

# Тест деректері
np.random.seed(0)
X_train = np.column_stack([np.ones(20), np.random.randn(20)])  # Бір фичалы деректер
y_train = 3 * X_train[:, 1] + 5 + np.random.randn(20) * 0.5  # y = 3x + 5 + шу

# КОДТЫ ОСЫНДА ЖАЗ
import numpy as np

class BaseModel:
    def __init__(self, model_name):
        self.model_name = model_name

    def fit(self, X, y):
        raise NotImplementedError("fit() әдісі туынды класта жазылуы керек")

    def predict(self, X):
        raise NotImplementedError("predict() әдісі туынды класта жазылуы керек")

    def describe(self):
        print(f"Model name: {self.model_name}")



class LinearRegressionModel(BaseModel):
    def __init__(self, model_name="Linear Regression"):
        super().__init__(model_name)
        self.weights = None

    def fit(self, X, y):

        self.weights, _, _, _ = np.linalg.lstsq(X, y, rcond=None)

    def predict(self, X):

        return X @ self.weights

    def describe(self):
        super().describe()
        print("Model coefficients:", self.weights)


model = LinearRegressionModel()

model.fit(X_train, y_train)

predictions = model.predict(X_train)

print("Predictions (first 5):")
print(predictions[:5])

model.describe()

Predictions (first 5):
[10.39296444  6.21801927  7.98908139 11.85259602 10.70979994]
Model name: Linear Regression
Model coefficients: [4.99311982 3.06104557]


## !КҮРДЕЛІ
##Тапсырма 10: Толыққанды ML Pipeline Класы

**Мақсат:** Нақты ML жүйесін модельдейтін толыққанды Pipeline класын жазу.

ML Pipeline  деректерді алдын ала өңдеу, модельді оқыту және бағалау қадамдарын автоматты реттілікпен орындайтын құрылым. sklearn-дің `Pipeline` класы осындай принципте жұмыс істейді. Мұны өз бетімен жүзеге асыру бүкіл ML жұмыс ағынын терең түсінуге мүмкіндік береді.

**Шарт:**

`MLPipeline` класы жаз, ол мынадай кезең-кезеңді іске асырсын:

1. **`load_data(X, y)`** — деректерді сақтайды
2. **`train_test_split(test_ratio=0.2)`** — деректерді оқыту/тест жиынтықтарына бөледі
3. **`normalize()`** — оқыту жиынтығы бойынша Min-Max нормализациясын жасайды (тест жиынына да қолданады)
4. **`train()`** — `np.linalg.lstsq` арқылы линейлі регрессия оқытады
5. **`evaluate()`** — MSE және R² метрикаларын есептейді
6. **`run()`** — барлық қадамдарды дұрыс ретпен шақырады

Тест деректерінде толық `run()` жүргіз және нәтижені шығар.

> **Кеңес:** R² = 1 - SS_res / SS_tot, мұндағы SS_res = Σ(y - ŷ)², SS_tot = Σ(y - ȳ)²

In [16]:
# Тапсырма 10: Толыққанды ML Pipeline класы

# Тест деректері
np.random.seed(42)
n_samples = 100
X_data = np.random.randn(n_samples, 3)  # 100 үлгі, 3 белгі
y_data = 2 * X_data[:, 0] - 1.5 * X_data[:, 1] + 0.5 * X_data[:, 2] + np.random.randn(n_samples) * 0.3

# КОДТЫ ОСЫНДА ЖАЗ
class MLPipeline:

    def __init__(self):
        self.X = None
        self.y = None
        self.X_train = None
        self.X_test = None
        self.y_train = None
        self.y_test = None
        self.weights = None
        self.xmin = None
        self.xmax = None

    # 1. Деректерді сақтау
    def load_data(self, X, y):
        self.X = X
        self.y = y

    # 2. Train/Test бөлу
    def train_test_split(self, test_ratio=0.2):
        n = len(self.X)
        split_index = int(n * (1 - test_ratio))

        self.X_train = self.X[:split_index]
        self.X_test = self.X[split_index:]

        self.y_train = self.y[:split_index]
        self.y_test = self.y[split_index:]

    # 3. Min-Max нормализация
    def normalize(self):
        self.xmin = self.X_train.min(axis=0)
        self.xmax = self.X_train.max(axis=0)

        self.X_train = (self.X_train - self.xmin) / (self.xmax - self.xmin)
        self.X_test = (self.X_test - self.xmin) / (self.xmax - self.xmin)

    # 4. Модельді оқыту (Linear Regression)
    def train(self):
        X_train_bias = np.column_stack([np.ones(len(self.X_train)), self.X_train])
        self.weights, _, _, _ = np.linalg.lstsq(X_train_bias, self.y_train, rcond=None)

    # 5. Бағалау (MSE және R²)
    def evaluate(self):
        X_test_bias = np.column_stack([np.ones(len(self.X_test)), self.X_test])

        y_pred = X_test_bias @ self.weights

        mse = np.mean((self.y_test - y_pred) ** 2)

        ss_res = np.sum((self.y_test - y_pred) ** 2)
        ss_tot = np.sum((self.y_test - np.mean(self.y_test)) ** 2)

        r2 = 1 - ss_res / ss_tot

        print("MSE:", mse)
        print("R²:", r2)

    # 6. Pipeline толық орындау
    def run(self):
        self.train_test_split()
        self.normalize()
        self.train()
        self.evaluate()
pipeline = MLPipeline()

pipeline.load_data(X_data, y_data)

pipeline.run()

MSE: 0.11711216530265836
R²: 0.9827905620387998


# Қорытынды және Өзін-өзі Бағалау

(міндетті емес) Барлық тапсырмаларды орындап болған соң, төмендегі кестені толтыр:

| Тапсырма | Тақырып | Орындалды? | Қиындықтар |
|:--------:|---------|:----------:|------------|
| 1 | NumPy массиві және сипаттамалар | ☐ | |
| 2 | Матрица және матрицалық операциялар | ☐ | |
| 3 | Индекстеу және сүзгілеу | ☐ | |
| 4 | Статистикалық функциялар | ☐ | |
| 5 | Reshape және Broadcasting | ☐ | |
| 6 | Нормализация функциялары | ☐ | |
| 7 | Рекурсия және Lambda | ☐ | |
| 8 | ClassificationMetrics класы | ☐ | |
| 9 | Мұрагерлік — ML иерархиясы | ☐ | |
| 10 | ML Pipeline класы | ☐ | |

---

**Пікір (міндетті емес):**

_Осы үй жұмысын орындау барысында не үйрендің? Қандай тапсырма ең қызықты болды?_


---