<a href="https://colab.research.google.com/github/ansaganakhat/project-1/blob/main/%D0%9C%D0%9E_%D0%9C%D0%B0%D1%82%D0%B5%D0%BC%D0%B0%D1%82%D0%B8%D0%BA%D0%B0_%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Практика Машиналық оқытуға қажетті базалық Математика


**Мақсат:** Бұл практикалық жұмыста студенттер машиналық оқытуда кеңінен қолданылатын математикалық аппаратты — сызықтық алгебра, ықтималдық теориясы, статистика және нормализация әдістерін Python арқылы меңгереді.

**Нұсқау:** Әр ұяшықтағы `# TODO` белгісін тауып, тапсырманы орындаңыз. Код ұяшықтарын кезекпен іске қосыңыз.

| Студент | Орындайтын тапсырма |
| :--- | :--- |
| Амангелді Мейірім | 1.1, 2.1, 3.1, 4.1, 5.1 |
| Ахат Аңсаған | 1.2, 2.2, 3.2, 4.2, 5.2 |
| Бахрам Бексұлтан | 1.3, 2.3, 3.3, 4.3, 5.3 |
| Даирова Нұрсұлу | 1.4, 2.4, 3.4, 4.4, 5.4 |
| Жумадилов Дияр | 1.5, 2.5, 3.5, 4.5, 5.5 |
| Жүнісова Әсел | 1.6, 2.6, 3.6, 4.6, 5.6 |
| Кинаятов Наурызбай | 1.7, 2.7, 3.7, 4.7, 5.7 |
| Манапалы Жанерке | 1.8, 2.8, 3.8, 4.8, 5.8 |
| Саматқызы Амина | 1.9, 2.9, 3.9, 4.9, 5.9 |

In [1]:
# Қажетті кітапханаларды импорттау
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
from sklearn.preprocessing import MinMaxScaler, StandardScaler, normalize
import warnings
warnings.filterwarnings('ignore')

# Нәтижелердің қайталануын қамтамасыз ету
np.random.seed(42)
print("Кітапханалар сәтті жүктелді!")

Кітапханалар сәтті жүктелді!


# 1-БӨЛІМ: Векторлар және матрицалар

**Мақсат:** Векторлар мен матрицалардың негізгі операцияларын Python-да орындауды үйрену.

## Теориялық анықтама

**Вектор**  скалярлардың реттелген жиыны. $n$-өлшемді вектор:

$$\mathbf{x} = (x_1, x_2, \ldots, x_n)^T \in \mathbb{R}^n$$

**Матрица**  $m \times n$ өлшемді тіктөртбұрышты массив:

$$A = \begin{pmatrix} a_{11} & a_{12} \\ a_{21} & a_{22} \end{pmatrix}$$

**Скалярлық көбейтінді (dot product):**

$$\mathbf{a} \cdot \mathbf{b} = \sum_{i=1}^{n} a_i b_i = \|\mathbf{a}\| \|\mathbf{b}\| \cos\theta$$

In [4]:
# Тапсырма 1.2: Матрица жасау
# NumPy арқылы матрица операцияларын орындаңыз

# TODO: 3x3 өлшемді кез келген бүтін сандардан тұратын матрица жасаңыз
A = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
# TODO: 3x3 өлшемді бірлік матрица (identity matrix) жасаңыз
I = np.eye(3)

print(A@I)
# TODO: A матрицасының транспозициясын алыңыз
A_T = A.T
print(A_T)
print("A матрицасы:\n", A)
print("Бірлік матрица I:\n", I)
print("A матрицасының транспозициясы:\n", A_T)

[[10. 20. 30.]
 [40. 50. 60.]
 [70. 80. 90.]]
[[10 40 70]
 [20 50 80]
 [30 60 90]]
A матрицасы:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Бірлік матрица I:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
A матрицасының транспозициясы:
 [[10 40 70]
 [20 50 80]
 [30 60 90]]


In [ ]:
# Тапсырма 1.1: Вектор жасау және негізгі операциялар
# Екі вектор беріледі, олардың қосындысын, айырмасын және скалярлық көбейтіндісін есептеңіз

a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])

# TODO: a және b векторларының қосындысын есептеңіз
addition = None

# TODO: a және b векторларының айырмасын есептеңіз
subtraction = None

# TODO: a және b векторларының скалярлық көбейтіндісін есептеңіз
dot_product = None

print("Вектор a:", a)
print("Вектор b:", b)
print("Қосынды:", addition)
print("Айырма:", subtraction)
print("Скалярлық көбейтінді:", dot_product)

In [ ]:
# Тапсырма 1.3: Матрицаларды көбейту
# Матрица-вектор және матрица-матрица көбейтіндісін орындаңыз

A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.array([[7, 8, 9], [10, 11, 12]])

# TODO: A және B матрицаларын көбейтіңіз (матрица көбейтіндісі)
C = None

# TODO: C матрицасының пішінін (shape) анықтаңыз
C_shape = None

print("A матрицасы (3x2):\n", A)
print("B матрицасы (2x3):\n", B)
print("C = A @ B нәтижесі:\n", C)
print("C матрицасының пішіні:", C_shape)

In [ ]:
# Тапсырма 1.4: Кері матрица
# Матрицаның детерминантын және кері матрицасын есептеңіз

M = np.array([[2, 1], [5, 3]])

# TODO: M матрицасының детерминантын есептеңіз
det_M = None

# TODO: M матрицасының кері матрицасын есептеңіз
M_inv = None

# TODO: M @ M_inv = I екенін тексеріңіз (бірлік матрица шығуы тиіс)
check = None

print("M матрицасы:\n", M)
print("Детерминант:", det_M)
print("Кері матрица:\n", M_inv)
print("M @ M_inv тексерісі:\n", check)

In [ ]:
# Тапсырма 1.5: Меншікті мәндер мен меншікті векторлар
# Eigenvalues және eigenvectors машиналық оқытудағы PCA алгоритмінің негізі болып табылады

S = np.array([[4, 2], [1, 3]])

# TODO: S матрицасының меншікті мәндерін (eigenvalues) есептеңіз
eigenvalues = None

# TODO: S матрицасының меншікті векторларын (eigenvectors) есептеңіз
eigenvectors = None

print("S матрицасы:\n", S)
print("Меншікті мәндер:", eigenvalues)
print("Меншікті векторлар:\n", eigenvectors)

In [ ]:
# Тапсырма 1.6: Вектор операцияларын визуализациялау
# Екі 2D векторды және олардың қосындысын график арқылы көрсетіңіз

v1 = np.array([3, 1])
v2 = np.array([1, 3])

# TODO: v1 және v2 векторларының қосындысын есептеңіз
v_sum = None

fig, ax = plt.subplots(figsize=(6, 6))
origin = np.array([0, 0])

# TODO: ax.quiver() арқылы v1, v2, v_sum векторларын салыңыз
# Мысалы: ax.quiver(*origin, *v1, color='blue', scale=1, scale_units='xy', angles='xy', label='v1')

ax.set_xlim(-1, 6)
ax.set_ylim(-1, 6)
ax.axhline(0, color='black', linewidth=0.5)
ax.axvline(0, color='black', linewidth=0.5)
ax.grid(True)
ax.legend()
ax.set_title("Вектор қосындысы")
plt.show()

In [ ]:
# Тапсырма 1.7: Сызықтық теңдеулер жүйесін шешу
# Ax = b жүйесін матрицалық тәсілмен шешіңіз

# Жүйе: 2x + y = 5, x + 3y = 10
A = np.array([[2, 1], [1, 3]])
b = np.array([5, 10])

# TODO: numpy.linalg.solve() арқылы x = (x1, x2) шешімін табыңыз
x = None

# TODO: шешімді тексеріңіз: A @ x берілген b-ға тең болуы тиіс
verification = None

print("A матрицасы:\n", A)
print("b векторы:", b)
print("Шешім x:", x)
print("Тексеріс A@x:", verification)

In [ ]:
# Тапсырма 1.8: SVD ыдырату
# Singular Value Decomposition (SVD) — деректерді қысудың негізгі тәсілі

X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

# TODO: X матрицасын SVD ыдыратуды орындаңыз: U, S, Vt алыңыз
U, S, Vt = None, None, None

# TODO: S векторынан диагональ матрица жасаңыз (np.diag)
Sigma = None

# TODO: X матрицасын U @ Sigma @ Vt арқылы қайта жасаңыз
X_reconstructed = None

print("Сингулярлық мәндер S:", S)
print("U пішіні:", U.shape if U is not None else None)
print("Қайта жасалған матрица:\n", X_reconstructed)

In [ ]:
# Тапсырма 1.9: Матрицаның дәрежесі мен ізі
# Rank және trace — матрица қасиеттерін сипаттайтын маңызды шамалар

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[1, 0, 0], [0, 2, 0], [0, 0, 3]])

# TODO: A матрицасының дәрежесін (rank) есептеңіз
rank_A = None

# TODO: B матрицасының ізін (trace) — диагональ элементтер қосындысын есептеңіз
trace_B = None

# TODO: B матрицасының Frobenius нормасын есептеңіз
frobenius_norm = None

print("A матрицасының дәрежесі:", rank_A)
print("B матрицасының ізі:", trace_B)
print("B матрицасының Frobenius нормасы:", frobenius_norm)

In [ ]:
# Тапсырма 1.10: Косинустық ұқсастық
# Ұсыныс жүйелері мен мәтіндік талдауда кеңінен қолданылады
# Формула: cos(θ) = (a · b) / (||a|| * ||b||)

def cosine_similarity(vec1, vec2):
    # TODO: скалярлық көбейтіндіні есептеңіз
    dot = None
    # TODO: vec1 нормасын есептеңіз
    norm1 = None
    # TODO: vec2 нормасын есептеңіз
    norm2 = None
    # TODO: косинустық ұқсастықты қайтарыңыз
    return None

u = np.array([1, 2, 3])
v = np.array([4, 5, 6])
w = np.array([-1, -2, -3])

print("u және v ұқсастығы:", cosine_similarity(u, v))
print("u және w ұқсастығы:", cosine_similarity(u, w))
print("u және u ұқсастығы:", cosine_similarity(u, u))

# 2-БӨЛІМ: Векторлық нормалар

**Мақсат:** Машиналық оқытудың реттеу (regularization) әдістерінде қолданылатын нормаларды есептеуді меңгеру.

## Теориялық анықтама

**L1 норма (Manhattan):**

$$\|\mathbf{x}\|_1 = \sum_{i=1}^{n} |x_i|$$

**L2 норма (Euclidean):**

$$\|\mathbf{x}\|_2 = \sqrt{\sum_{i=1}^{n} x_i^2}$$

**L$\infty$ норма (Chebyshev):**

$$\|\mathbf{x}\|_{\infty} = \max_i |x_i|$$

Lasso регрессиясы L1 нормасын, Ridge регрессиясы L2 нормасын қолданады.

In [11]:
# Тапсырма 2.2: L2 нормасын қолмен есептеу
# Евклидтік қашықтық — ML-де ең жиі қолданылатын норма

x = np.array([3, -4, 0, 2, -1])

# TODO: L2 нормасын NumPy операцияларын қолданбай қолмен есептеңіз
l2_manual = np.sqrt(sum([xi**2 for xi in x]))

# TODO: np.linalg.norm() арқылы L2 нормасын тексеріңіз
l2_numpy = np.linalg.norm(x)

print("Вектор x:", x)
print("L2 норма (қолмен):", l2_manual)
print("L2 норма (NumPy):", l2_numpy)

Вектор x: [ 3 -4  0  2 -1]
L2 норма (қолмен): 5.477225575051661
L2 норма (NumPy): 5.477225575051661


In [ ]:
# Тапсырма 2.1: L1 нормасын қолмен есептеу
# L1 норма — элементтер модульдерінің қосындысы

x = np.array([3, -4, 0, 2, -1])

# TODO: L1 нормасын NumPy операцияларын қолданбай қолмен есептеңіз
l1_manual = None

# TODO: np.linalg.norm() арқылы L1 нормасын тексеріңіз
l1_numpy = None

print("Вектор x:", x)
print("L1 норма (қолмен):", l1_manual)
print("L1 норма (NumPy):", l1_numpy)
print("Нәтижелер сәйкес келеді:", np.isclose(l1_manual, l1_numpy))

In [ ]:
# Тапсырма 2.3: Lp нормасын жалпылама функция арқылы есептеу

def lp_norm(x, p):
    # TODO: p параметрі бойынша Lp нормасын есептейтін функция жазыңыз
    # Формула: (sum(|xi|^p))^(1/p)
    return None

x = np.array([1.0, -2.0, 3.0, -4.0])

# TODO: p=1, 2, 3, 10 үшін нормаларды есептеңіз
for p in [1, 2, 3, 10]:
    print(f"L{p} норма: {lp_norm(x, p):.4f}")

In [ ]:
# Тапсырма 2.4: Нормаларды визуализациялау — L1 және L2 шарлары
# Бірлік шарлардың пішіні реттеу әдісінің қасиеттерін анықтайды

theta = np.linspace(0, 2 * np.pi, 1000)

# L2 бірлік шары: x^2 + y^2 = 1
x_l2 = np.cos(theta)
y_l2 = np.sin(theta)

# L1 бірлік шары: |x| + |y| = 1 (ромб)
# TODO: L1 бірлік шарының x және y координаттарын есептеңіз
# Кеңес: t = linspace(-1, 1), жоғарғы жағы: y = 1 - |t|, төменгі: y = -(1 - |t|)
t = np.linspace(-1, 1, 500)
x_l1 = None
y_l1_upper = None
y_l1_lower = None

fig, axes = plt.subplots(1, 2, figsize=(12, 5))

axes[0].plot(x_l2, y_l2, 'b-', linewidth=2)
axes[0].set_title("L2 бірлік шары (эллипс)")
axes[0].set_aspect('equal')
axes[0].grid(True)

if x_l1 is not None:
    axes[1].plot(x_l1, y_l1_upper, 'r-', linewidth=2)
    axes[1].plot(x_l1, y_l1_lower, 'r-', linewidth=2)
axes[1].set_title("L1 бірлік шары (ромб)")
axes[1].set_aspect('equal')
axes[1].grid(True)

plt.tight_layout()
plt.show()

In [ ]:
# Тапсырма 2.5: Евклидтік қашықтық
# K-NN алгоритмінің негізгі операциясы нүктелер арасындағы қашықтықты өлшеу

def euclidean_distance(p1, p2):
    # TODO: екі нүкте арасындағы евклидтік қашықтықты есептеңіз
    return None

def manhattan_distance(p1, p2):
    # TODO: екі нүкте арасындағы Манхэттен қашықтығын есептеңіз
    return None

p1 = np.array([1, 2, 3])
p2 = np.array([4, 6, 8])

print("p1 нүктесі:", p1)
print("p2 нүктесі:", p2)
print("Евклидтік қашықтық:", euclidean_distance(p1, p2))
print("Манхэттен қашықтығы:", manhattan_distance(p1, p2))

In [ ]:
# Тапсырма 2.6: Нормаланған вектор (unit vector)
# Нормалау — векторды бірлік ұзындыққа келтіру
# Формула: x_hat = x / ||x||_2

def normalize_vector(x):
    # TODO: берілген векторды нормалаңыз (бірлік вектор алыңыз)
    return None

v = np.array([3.0, 4.0])

v_normalized = normalize_vector(v)

print("Бастапқы вектор:", v)
print("Нормаланған вектор:", v_normalized)
print("Нормаланған вектордың L2 нормасы (1.0 болуы тиіс):", np.linalg.norm(v_normalized))

In [ ]:
# Тапсырма 2.7: Матрица нормасы және шарт саны
# Condition number жүйенің сандық тұрақтылығын көрсетеді

# Жақсы шартталған матрица
A_good = np.array([[2.0, 0], [0, 3.0]])

# Нашар шартталған матрица
A_bad = np.array([[1.0, 1.0], [1.0, 1.001]])

# TODO: A_good матрицасының шарт санын (condition number) есептеңіз
cond_good = None

# TODO: A_bad матрицасының шарт санын есептеңіз
cond_bad = None

print("Жақсы матрицаның шарт саны:", cond_good)
print("Нашар матрицаның шарт саны:", cond_bad)
print("Шарт саны үлкен болса, матрица нашар шартталған деп саналады")

In [ ]:
# Тапсырма 2.8: Векторлар арасындағы бұрыш
# Скалярлық көбейтінді арқылы бұрышты табу
# cos(θ) = (a · b) / (||a|| * ||b||)

def angle_between(v1, v2, degrees=True):
    # TODO: екі вектор арасындағы бұрышты есептеңіз
    cos_theta = None
    angle_rad = None
    if degrees:
        # TODO: радианды градусқа аударыңыз
        return None
    return angle_rad

a = np.array([1, 0])
b = np.array([0, 1])
c = np.array([1, 1])

print("a және b арасындағы бұрыш (градус):", angle_between(a, b))
print("a және c арасындағы бұрыш (градус):", angle_between(a, c))
print("a және a арасындағы бұрыш (градус):", angle_between(a, a))

In [ ]:
# Тапсырма 2.9: Вектордың проекциясы
# a векторының b бағытына проекциясы
# proj_b(a) = (a · b / ||b||^2) * b

def vector_projection(a, b):
    # TODO: a векторының b бағытына проекциясын есептеңіз
    scalar_proj = None
    vector_proj = None
    return vector_proj

a = np.array([3.0, 2.0])
b = np.array([1.0, 0.0])

proj = vector_projection(a, b)
print("a векторы:", a)
print("b векторы:", b)
print("a-ның b-ға проекциясы:", proj)

In [ ]:
# Тапсырма 2.10: Нормаларды салыстыру — жиынтық есеп
# Әр норманың мәнін кесте түрінде шығарыңыз

vectors = [
    np.array([1, 0, 0, 0]),
    np.array([1, 1, 0, 0]),
    np.array([1, 1, 1, 0]),
    np.array([1, 1, 1, 1]),
]

print(f"{'Вектор':<25} {'L1':>8} {'L2':>8} {'L-inf':>8}")
print("-" * 55)

for v in vectors:
    # TODO: әр вектор үшін L1, L2, L-inf нормаларын есептеңіз
    l1 = None
    l2 = None
    linf = None
    print(f"{str(v):<25} {l1 if l1 is not None else 'TODO':>8} {l2 if l2 is not None else 'TODO':>8} {linf if linf is not None else 'TODO':>8}")


# 3-БӨЛІМ: Ықтималдық теориясы негіздері

**Мақсат:** Машиналық оқытудағы байесиандық тәсілдер мен ықтималдық модельдерінің негізін қалайтын ықтималдық теориясын меңгеру.

## Теориялық анықтама

**Байес теоремасы:**

$$P(A|B) = \frac{P(B|A) \cdot P(A)}{P(B)}$$

$P(A|B)$ — Шартты ықтималдық: $B$ жаңа оқиғасы орындалып қойған кездегі $A$ оқиғасының ықтималдығы (біздің жаңартылған болжамымыз).

$P(A)$ — Априорлық ықтималдық: Жаңа мәліметті білмей тұрғандағы $A$-ның бастапқы ықтималдығы.

**Математикалық үміт:**

Кездейсоқ шаманың күтілетін "орташа" мәні. Бұл алгоритм ұзақ мерзімде немесе үлкен мәліметтер жиынтығында қандай нәтижеге қол жеткізетінін көрсетеді.

$$E[X] = \sum_{x} x \cdot P(X = x)$$

Қарапайым тілмен: Мұндағы әрбір мүмкін мән ($x$) өзінің кездесу ықтималдығына ($P(X = x)$) көбейтіліп, бір-біріне қосылады.


**Дисперсия:**


Мәліметтердің орташа мәннен (математикалық үміттен) қаншалықты ауытқитынын көрсетеді. Дисперсия неғұрлым жоғары болса, мәліметтер соғұрлым тұрақсыз әрі шашыраңқы болады. Бұл модельдің қателіктерін бағалауда маңызды рөл атқарады.

$$\text{Var}(X) = E[(X - E[X])^2] = E[X^2] - (E[X])^2$$



**Ковариация:**

Екі түрлі айнымалының (мәліметтердегі екі түрлі бағанның) бірге қалай өзгеретінін көрсетеді. Машиналық оқытуда бұл бір-бірін қайталайтын, артық белгілерді (features) тауып, алып тастау үшін қажет.

$$\text{Cov}(X, Y) = E[(X - \mu_X)(Y - \mu_Y)]$$



In [12]:
# Тапсырма 3.2: Математикалық үміт және дисперсия
# Тасымалдаушының жұмыс ақысы — дискретті кездейсоқ шама

# Кіріс: пайда мәндері және олардың ықтималдықтары
values = np.array([100, 200, 300, 400, 500])
probabilities = np.array([0.1, 0.2, 0.4, 0.2, 0.1])

# TODO: ықтималдықтар қосындысының 1.0 екенін тексеріңіз
prob_sum = probabilities.sum()

# TODO: математикалық үмітті (E[X]) есептеңіз
expected_value = np.sum(values * probabilities)

# TODO: дисперсияны (Var(X)) есептеңіз
E_X2=np.sum((values**2)*probabilities)
variance = E_X2-expected_value**2

# TODO: стандартты ауытқуды (std) есептеңіз
std_dev = np.sqrt(variance)

print(f"Ықтималдықтар қосындысы: {prob_sum}")
print(f"Математикалық үміт E[X]: {expected_value}")
print(f"Дисперсия Var(X): {variance}")
print(f"Стандартты ауытқу: {std_dev:.4f}")

Ықтималдықтар қосындысы: 1.0000000000000002
Математикалық үміт E[X]: 300.0
Дисперсия Var(X): 12000.0
Стандартты ауытқу: 109.5445


In [ ]:
# Тапсырма 3.1: Байес теоремасы — медициналық тест мысалы
# Аурудың таралуы 1% (P(D)), тест сезімталдығы 99% (P(+|D))
# Жалған оң нәтиже 5% (P(+|~D))
# Оң нәтиже алған адамның нақты ауру екендігін табыңыз

P_D = 0.01        # аурудың алдын ала ықтималдығы
P_pos_given_D = 0.99    # тест оң, адам ауру
P_pos_given_not_D = 0.05  # жалған оң нәтиже

# TODO: аурудың алдын ала болмау ықтималдығын есептеңіз
P_not_D = None

# TODO: оң нәтиже алу жалпы ықтималдығын есептеңіз: P(+)
P_pos = None

# TODO: Байес теоремасы бойынша P(D|+) есептеңіз
P_D_given_pos = None

print(f"Тест оң болса, аурудың нақты болу ықтималдығы: {P_D_given_pos:.4f} ({P_D_given_pos*100:.2f}%)")

In [ ]:
# Тапсырма 3.3: Биномдық таралым
# n тәжірибедегі k сәтті нәтиже ықтималдығы
# P(X=k) = C(n,k) * p^k * (1-p)^(n-k)

from scipy.stats import binom

n = 10    # тәжірибелер саны
p = 0.3   # сәтті нәтиже ықтималдығы

# TODO: k = 0, 1, ..., n үшін PMF мәндерін есептеңіз
k_values = np.arange(0, n + 1)
pmf_values = None

# TODO: графикті салыңыз
if pmf_values is not None:
    plt.figure(figsize=(9, 4))
    plt.bar(k_values, pmf_values, color='steelblue', alpha=0.8)
    plt.xlabel("k (сәтті нәтижелер саны)")
    plt.ylabel("P(X = k)")
    plt.title(f"Биномдық таралым (n={n}, p={p})")
    plt.xticks(k_values)
    plt.grid(axis='y', alpha=0.3)
    plt.show()

# TODO: үміт мен дисперсияны аналитикалық формулалармен есептеңіз
mean_binom = None  # E[X] = n*p
var_binom = None   # Var(X) = n*p*(1-p)
print(f"Үміт: {mean_binom}, Дисперсия: {var_binom}")

In [ ]:
# Тапсырма 3.4: Пуассон таралымы
# Белгілі уақыт аралығында болатын оқиғалар санын модельдейді
# P(X=k) = (lambda^k * e^(-lambda)) / k!

from scipy.stats import poisson

lambda_val = 5  # орташа оқиғалар саны (сағатына)

# TODO: k = 0..15 үшін PMF есептеңіз
k_values = np.arange(0, 16)
pmf_poisson = None

# TODO: k = 0..15 үшін CDF есептеңіз
cdf_poisson = None

if pmf_poisson is not None:
    fig, axes = plt.subplots(1, 2, figsize=(12, 4))
    axes[0].bar(k_values, pmf_poisson, color='coral', alpha=0.8)
    axes[0].set_title(f"Пуассон PMF (λ={lambda_val})")
    axes[0].set_xlabel("k")
    axes[0].set_ylabel("P(X=k)")
    axes[0].grid(axis='y', alpha=0.3)

    if cdf_poisson is not None:
        axes[1].step(k_values, cdf_poisson, color='green', where='post')
        axes[1].set_title(f"Пуассон CDF (λ={lambda_val})")
        axes[1].set_xlabel("k")
        axes[1].set_ylabel("P(X ≤ k)")
        axes[1].grid(alpha=0.3)

    plt.tight_layout()
    plt.show()

In [ ]:
# Тапсырма 3.5: Ковариация матрицасы
# Айнымалылар арасындағы сызықтық байланысты өлшейді

np.random.seed(0)
# Байланысты деректерді модельдеу
x = np.random.randn(100)
y = 2 * x + np.random.randn(100) * 0.5  # x-ке тәуелді
z = np.random.randn(100)                 # тәуелсіз

data = np.vstack([x, y, z])  # 3 x 100 матрица

# TODO: np.cov() арқылы ковариация матрицасын есептеңіз
cov_matrix = None

print("Ковариация матрицасы:\n", cov_matrix)
print("\nx және y арасындағы ковариация:", cov_matrix[0, 1] if cov_matrix is not None else "TODO")
print("x және z арасындағы ковариация:", cov_matrix[0, 2] if cov_matrix is not None else "TODO")

In [ ]:
# Тапсырма 3.6: Корреляция коэффициенті
# Pearson корреляциясы [-1, 1] аралығындағы байланыс күшін көрсетеді
# r = Cov(X,Y) / (std(X) * std(Y))

def pearson_correlation(x, y):
    # TODO: Pearson корреляция коэффициентін есептеңіз
    return None

np.random.seed(1)
x = np.random.randn(200)
y_strong = 3 * x + np.random.randn(200) * 0.1   # күшті оң байланыс
y_weak = np.random.randn(200)                     # байланыс жоқ
y_neg = -2 * x + np.random.randn(200) * 0.5      # теріс байланыс

print("Күшті оң байланыс r:", pearson_correlation(x, y_strong))
print("Байланыссыз r:", pearson_correlation(x, y_weak))
print("Теріс байланыс r:", pearson_correlation(x, y_neg))

In [ ]:
# Тапсырма 3.7: Монте-Карло симуляциясы
# Кездейсоқ таңдау арқылы π санын бағалаңыз

def estimate_pi(n_samples):
    # TODO: [-1,1]x[-1,1] аймағында n_samples нүктені кездейсоқ жасаңыз
    x = None
    y = None
    # TODO: бірлік шар ішіндегі нүктелер санын есептеңіз (x^2 + y^2 <= 1)
    inside = None
    # TODO: π-ды бағалаңыз: π ≈ 4 * (ішіндегі / барлық)
    pi_estimate = None
    return pi_estimate

for n in [100, 1000, 10000, 100000]:
    pi_est = estimate_pi(n)
    print(f"n={n:>7}: π ≈ {pi_est:.6f}  (қате: {abs(pi_est - np.pi):.6f})" if pi_est else f"n={n}: TODO")

In [ ]:
# Тапсырма 3.8: Шартты ықтималдық — жалған оң нәтижелерді талдау
# Спам сүзгісінің нақтылығын бағалаңыз

# Берілген мәліметтер:
total_emails = 1000
spam_emails = 200        # шын спам
ham_emails = 800         # шын хат
spam_detected = 180      # спам дұрыс анықталды (True Positive)
ham_as_spam = 40         # хат спам деп белгіленді (False Positive)

# TODO: спамды дұрыс анықтау ықтималдығын есептеңіз P(detected | spam)
P_detected_given_spam = None

# TODO: спам деп белгіленген хаттар ішінде шын спам ықтималдығы — P(spam | detected)
P_spam_given_detected = None  # Байес теоремасы арқылы

# TODO: дәлдікті (precision) есептеңіз: TP / (TP + FP)
precision = None

# TODO: толықтықты (recall) есептеңіз: TP / (TP + FN)
recall = None

print(f"P(анықталды | спам) = {P_detected_given_spam}")
print(f"P(спам | анықталды) = {P_spam_given_detected}")
print(f"Дәлдік (Precision): {precision}")
print(f"Толықтық (Recall): {recall}")

In [ ]:
# Тапсырма 3.9: Үлкен сандар заңы
# Таңдама өлшемі ұлғайған сайын орта мән нақты мәнге жақындайды

true_mean = 0.5   # p=0.5 монета лақтыру нәтижесі
n_max = 1000

# TODO: np.random.binomial(1, true_mean, n_max) арқылы монета лақтыру симуляциясын орындаңыз
flips = None

# TODO: 1-ден n_max-ке дейін жиіліктің жинақталған орта мәнін есептеңіз
# Кеңес: np.cumsum(flips) / np.arange(1, n_max+1)
cumulative_means = None

if cumulative_means is not None:
    plt.figure(figsize=(10, 4))
    plt.plot(cumulative_means, color='blue', alpha=0.7, label='Жинақталған орта')
    plt.axhline(true_mean, color='red', linestyle='--', label=f'Нақты мән = {true_mean}')
    plt.xlabel("Тәжірибелер саны")
    plt.ylabel("Орта мән")
    plt.title("Үлкен сандар заңы — монета лақтыру симуляциясы")
    plt.legend()
    plt.grid(alpha=0.3)
    plt.show()

In [ ]:
# Тапсырма 3.10: Орталық шек теоремасы (ОШТ)
# n үлкен болған кезде таңдама ортасының таралымы нормальға жақындайды

from scipy.stats import norm

def demonstrate_clt(distribution_samples, n_per_sample, n_experiments):
    sample_means = []
    for _ in range(n_experiments):
        # TODO: distribution_samples ішінен n_per_sample элементті таңдап, ортасын есептеңіз
        sample = None
        mean = None
        if mean is not None:
            sample_means.append(mean)
    return np.array(sample_means)

# Біркелкі таралымнан деректер
uniform_data = np.random.uniform(0, 1, 100000)

for n in [1, 5, 30]:
    means = demonstrate_clt(uniform_data, n, 1000)
    if len(means) > 0:
        plt.figure(figsize=(7, 3))
        plt.hist(means, bins=50, density=True, alpha=0.7, color='steelblue')
        plt.title(f"ОШТ: n={n} таңдама өлшемі")
        plt.xlabel("Таңдама ортасы")
        plt.ylabel("Тығыздық")
        plt.grid(alpha=0.3)
        plt.show()


# 4-БӨЛІМ: Статистикалық таралымдар

**Мақсат:** Машиналық оқытуда кеңінен қолданылатын негізгі статистикалық таралымдарды зерттеу және олардың қасиеттерін меңгеру.

## Теориялық анықтама

**Қалыпты (нормаль) таралым:**

$$f(x) = \frac{1}{\sigma\sqrt{2\pi}} \exp\left(-\frac{(x-\mu)^2}{2\sigma^2}\right)$$

**Экспоненциалды таралым:**

$$f(x) = \lambda e^{-\lambda x}, \quad x \geq 0$$

**68-95-99.7 ережесі:** Нормаль таралымда деректердің 68% $\mu \pm \sigma$, 95% $\mu \pm 2\sigma$, 99.7% $\mu \pm 3\sigma$ аралығында орналасады.

In [7]:
# Тапсырма 4.2: 68-95-99.7 ережесін тексеру
# Стандартты нормаль таралымнан үлкен таңдама алып, ережені тексеріңіз

np.random.seed(42)
samples = np.random.normal(0, 1, 100000)

# TODO: |x| <= 1 шартын қанағаттандыратын элементтер үлесін есептеңіз (%)
within_1sigma = np.mean(np.abs(samples) <= 1) * 100

# TODO: |x| <= 2 шартын қанағаттандыратын элементтер үлесін есептеңіз (%)
within_2sigma = np.mean(np.abs(samples) <= 2) * 100

# TODO: |x| <= 3 шартын қанағаттандыратын элементтер үлесін есептеңіз (%)
within_3sigma = np.mean(np.abs(samples) <= 3) * 100

print("68-95-99.7 ережесін тексеру:")
print(f"  ±1σ аралығында: {within_1sigma:.2f}%  (теория: 68.27%)")
print(f"  ±2σ аралығында: {within_2sigma:.2f}%  (теория: 95.45%)")
print(f"  ±3σ аралығында: {within_3sigma:.2f}%  (теория: 99.73%)")

68-95-99.7 ережесін тексеру:
  ±1σ аралығында: 68.16%  (теория: 68.27%)
  ±2σ аралығында: 95.45%  (теория: 95.45%)
  ±3σ аралығында: 99.74%  (теория: 99.73%)


In [ ]:
# Тапсырма 4.1: Нормаль таралым — PDF және CDF

from scipy.stats import norm

mu = 0
sigma = 1
x = np.linspace(-4, 4, 200)

# TODO: norm.pdf() арқылы ықтималдық тығыздық функциясын (PDF) есептеңіз
pdf_values = None

# TODO: norm.cdf() арқылы жинақталған таралым функциясын (CDF) есептеңіз
cdf_values = None

if pdf_values is not None and cdf_values is not None:
    fig, axes = plt.subplots(1, 2, figsize=(12, 4))

    axes[0].plot(x, pdf_values, 'b-', linewidth=2)
    axes[0].fill_between(x, pdf_values, alpha=0.2)
    axes[0].set_title(f"Нормаль таралым PDF (μ={mu}, σ={sigma})")
    axes[0].set_xlabel("x")
    axes[0].set_ylabel("f(x)")
    axes[0].grid(alpha=0.3)

    axes[1].plot(x, cdf_values, 'r-', linewidth=2)
    axes[1].set_title(f"Нормаль таралым CDF (μ={mu}, σ={sigma})")
    axes[1].set_xlabel("x")
    axes[1].set_ylabel("F(x)")
    axes[1].grid(alpha=0.3)

    plt.tight_layout()
    plt.show()

In [ ]:
# Тапсырма 4.3: Экспоненциалды таралым
# Оқиғалар арасындағы уақытты модельдейді (мысалы, тапсырыстар арасындағы уақыт)

from scipy.stats import expon

lambda_vals = [0.5, 1.0, 2.0]
x = np.linspace(0, 8, 300)

plt.figure(figsize=(10, 4))
for lam in lambda_vals:
    # TODO: expon.pdf() арқылы PDF мәндерін есептеңіз
    # Ескерту: scipy.stats.expon-да scale=1/lambda параметрі қолданылады
    pdf = None
    if pdf is not None:
        plt.plot(x, pdf, linewidth=2, label=f'λ={lam}')

plt.xlabel("x")
plt.ylabel("f(x)")
plt.title("Экспоненциалды таралым")
plt.legend()
plt.grid(alpha=0.3)
plt.show()

In [ ]:
# Тапсырма 4.4: Q-Q сызбасы арқылы нормальдылықты тексеру
# Q-Q plot — деректердің нормаль таралымға сәйкестігін визуалды тексеру

import scipy.stats as stats

np.random.seed(42)
normal_data = np.random.normal(5, 2, 500)
skewed_data = np.random.exponential(scale=2, size=500)

fig, axes = plt.subplots(1, 2, figsize=(12, 5))

# TODO: stats.probplot() арқылы normal_data үшін Q-Q сызбасын жасаңыз
# axes[0] ішіне сызыңыз

# TODO: stats.probplot() арқылы skewed_data үшін Q-Q сызбасын жасаңыз
# axes[1] ішіне сызыңыз

axes[0].set_title("Q-Q сызбасы: Нормаль деректер")
axes[1].set_title("Q-Q сызбасы: Асимметриялық деректер")

plt.tight_layout()
plt.show()

In [ ]:
# Тапсырма 4.5: Студент t-таралымы
# Кіші таңдамаларда нормаль таралым орнына қолданылады

from scipy.stats import t

x = np.linspace(-5, 5, 300)
df_values = [1, 3, 10, 30]

plt.figure(figsize=(9, 5))

for df in df_values:
    # TODO: t.pdf() арқылы t-таралымының PDF мәндерін есептеңіз
    pdf_t = None
    if pdf_t is not None:
        plt.plot(x, pdf_t, linewidth=2, label=f'df={df}')

# TODO: стандартты нормаль таралымды да қосыңыз (норма, sigma=1)
pdf_normal = None
if pdf_normal is not None:
    plt.plot(x, pdf_normal, 'k--', linewidth=2, label='Нормаль N(0,1)')

plt.xlabel("x")
plt.ylabel("Тығыздық")
plt.title("t-таралымы: еркіндік дәрежесі әсері")
plt.legend()
plt.grid(alpha=0.3)
plt.show()

In [ ]:
# Тапсырма 4.6: Гистограмма және ядролық тығыздық бағалауы (KDE)
# KDE — сыни деректер тығыздығын тегістеп бағалайды

from scipy.stats import gaussian_kde

np.random.seed(5)
# Екі нормаль компоненттен тұратын аралас таралым
data = np.concatenate([
    np.random.normal(-2, 0.5, 300),
    np.random.normal(3, 1.0, 500)
])

x_range = np.linspace(data.min() - 1, data.max() + 1, 300)

# TODO: gaussian_kde арқылы KDE объектісін жасаңыз
kde = None

# TODO: kde(x_range) арқылы KDE мәндерін есептеңіз
kde_values = None

plt.figure(figsize=(10, 4))
plt.hist(data, bins=50, density=True, alpha=0.5, color='steelblue', label='Гистограмма')
if kde_values is not None:
    plt.plot(x_range, kde_values, 'r-', linewidth=2, label='KDE')
plt.xlabel("x")
plt.ylabel("Тығыздық")
plt.title("Аралас нормаль таралым: Гистограмма және KDE")
plt.legend()
plt.grid(alpha=0.3)
plt.show()

In [ ]:
# Тапсырма 4.7: Chi-квадрат таралымы
# Гипотезаларды тексеруде және тәуелсіздік тесттерінде қолданылады

from scipy.stats import chi2

x = np.linspace(0, 30, 300)
df_values = [1, 2, 5, 10]

plt.figure(figsize=(9, 5))
for df in df_values:
    # TODO: chi2.pdf() арқылы PDF мәндерін есептеңіз
    pdf_chi2 = None
    if pdf_chi2 is not None:
        plt.plot(x, pdf_chi2, linewidth=2, label=f'df={df}')

plt.xlabel("x")
plt.ylabel("f(x)")
plt.ylim(0, 0.5)
plt.title("Chi-квадрат таралымы")
plt.legend()
plt.grid(alpha=0.3)
plt.show()

# TODO: 5 еркіндік дәрежесі, x=11.07 үшін p-мәнін есептеңіз (1 - CDF)
p_value = None
print(f"P(X > 11.07 | df=5) = {p_value:.4f} (0.05 болуы тиіс)")

In [ ]:
# Тапсырма 4.8: Сенімділік аралығы
# Орта мәнге 95% сенімділік аралығын есептеңіз

from scipy import stats

np.random.seed(42)
sample = np.random.normal(loc=10, scale=3, size=50)

# TODO: таңдама ортасы мен стандартты қатесін есептеңіз
sample_mean = None
standard_error = None  # std / sqrt(n)

# TODO: 95% сенімділік аралығын stats.t.interval() арқылы есептеңіз
confidence_interval = None

print(f"Таңдама ортасы: {sample_mean:.4f}")
print(f"Стандартты қате: {standard_error:.4f}")
print(f"95% сенімділік аралығы: {confidence_interval}")
print(f"Нақты орта мән (10.0) аралыққа кіреді: {confidence_interval[0] < 10.0 < confidence_interval[1] if confidence_interval else 'TODO'}")

In [ ]:
# Тапсырма 4.9: Деректерді трансформациялау — нормальдылыққа жақындату
# Log трансформация асимметриялық деректерді нормальдандырады

np.random.seed(7)
skewed_data = np.random.exponential(scale=2, size=1000)

# TODO: натуралды логарифм арқылы деректерді трансформациялаңыз
log_data = None

fig, axes = plt.subplots(1, 2, figsize=(12, 4))

axes[0].hist(skewed_data, bins=50, color='salmon', edgecolor='white', density=True)
axes[0].set_title("Бастапқы деректер (асимметриялы)")
axes[0].set_xlabel("Мән")
axes[0].set_ylabel("Тығыздық")
axes[0].grid(alpha=0.3)

if log_data is not None:
    axes[1].hist(log_data, bins=50, color='lightgreen', edgecolor='white', density=True)
axes[1].set_title("Log-трансформацияланған деректер")
axes[1].set_xlabel("log(мән)")
axes[1].set_ylabel("Тығыздық")
axes[1].grid(alpha=0.3)

plt.tight_layout()
plt.show()

# TODO: екі деректер жиынының асимметрия (skewness) көрсеткіштерін есептеңіз
print(f"Бастапқы деректер асимметриясы: {stats.skew(skewed_data):.4f}")
print(f"Log-трансформация асимметриясы: {stats.skew(log_data):.4f}" if log_data is not None else "Log-трансформация: TODO")

In [ ]:
# Тапсырма 4.10: Гипотезаларды тексеру — t-тест
# Екі топтың ортасы бірдей бе деген сұрақты статистикалық тексеру

from scipy import stats

np.random.seed(42)
# Бақылау тобы — дәрі берілмеген
control_group = np.random.normal(loc=100, scale=15, size=50)
# Эксперименталды топ — дәрі берілген
treatment_group = np.random.normal(loc=108, scale=15, size=50)

# TODO: stats.ttest_ind() арқылы тәуелсіз топтарды t-тест арқылы тексеріңіз
t_statistic, p_value = None, None

alpha = 0.05

print(f"Бақылау тобы ортасы: {control_group.mean():.2f}")
print(f"Эксперимент тобы ортасы: {treatment_group.mean():.2f}")
print(f"t-статистика: {t_statistic:.4f}" if t_statistic else "t-статистика: TODO")
print(f"p-мән: {p_value:.4f}" if p_value else "p-мән: TODO")
if p_value is not None:
    print(f"Шешім (alpha={alpha}): {'H0 қабылданбайды' if p_value < alpha else 'H0 қабылданады'}")


# 5-БӨЛІМ: Деректерді нормализациялау әдістері

**Мақсат:** Машиналық оқыту алгоритмдерінің дұрыс жұмыс істеуі үшін деректерді алдын ала өңдеу тәсілдерін меңгеру.

## Теориялық анықтама

**Min-Max нормализациясы:**

$$x_{\text{scaled}} = \frac{x - x_{\min}}{x_{\max} - x_{\min}} \in [0, 1]$$

**Z-score стандарттау:**

$$x_{\text{std}} = \frac{x - \mu}{\sigma}$$

**Robust нормализация:**

$$x_{\text{robust}} = \frac{x - \text{медиана}}{\text{IQR}}$$

IQR (Interquartile Range) — 75-ші және 25-ші перцентильдердің айырмасы. Аномалиялы мәндерге тұрақты.

In [13]:
# Тапсырма 5.2: Z-score стандарттауды қолмен орындау

def z_score_standardize(x):
    # TODO: Z-score стандарттауды орындайтын функция жазыңыз
    # Нәтиже: орта=0, std=1 болуы тиіс
    mean = x.mean()
    std = x.std()
    return (x-mean)/std

data = np.array([10.0, 20.0, 30.0, 40.0, 50.0])

standardized = z_score_standardize(data)

print("Бастапқы деректер:", data)
print("Z-score стандарттау:", standardized)
if standardized is not None:
    print(f"Орта (0-ге жақын болуы тиіс): {standardized.mean():.10f}")
    print(f"Стандартты ауытқу (1-ге жақын): {standardized.std():.10f}")

Бастапқы деректер: [10. 20. 30. 40. 50.]
Z-score стандарттау: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
Орта (0-ге жақын болуы тиіс): 0.0000000000
Стандартты ауытқу (1-ге жақын): 1.0000000000


In [9]:
# Тапсырма 5.1: Min-Max нормализациясын қолмен орындау

def min_max_normalize(x):
    # TODO: Min-Max нормализациясын орындайтын функция жазыңыз
    # Нәтиже [0, 1] аралығында болуы тиіс
    x_min = x.min()
    x_max = x.max()
    return (x-x_min)/(x_max - x_min)

data = np.array([10.0, 20.0, 30.0, 40.0, 50.0, 100.0])

normalized = min_max_normalize(data)

print("Бастапқы деректер:", data)
print("Min-Max нормализациясы:", normalized)
print("Минимум (0 болуы тиіс):", normalized.min() if normalized is not None else "TODO")
print("Максимум (1 болуы тиіс):", normalized.max() if normalized is not None else "TODO")

Бастапқы деректер: [ 10.  20.  30.  40.  50. 100.]
Min-Max нормализациясы: [0.         0.11111111 0.22222222 0.33333333 0.44444444 1.        ]
Минимум (0 болуы тиіс): 0.0
Максимум (1 болуы тиіс): 1.0


In [ ]:
# Тапсырма 5.3: Sklearn арқылы нормализациялау

from sklearn.preprocessing import MinMaxScaler, StandardScaler

np.random.seed(0)
data_2d = np.random.randn(100, 3) * np.array([10, 100, 0.1]) + np.array([5, -50, 2])

# TODO: MinMaxScaler арқылы нормализациялаңыз
mm_scaler = MinMaxScaler()
data_minmax = None

# TODO: StandardScaler арқылы стандарттаңыз
std_scaler = StandardScaler()
data_standard = None

print("Бастапқы деректер статистикасы:")
print(f"  Орта: {data_2d.mean(axis=0).round(2)}")
print(f"  Std:  {data_2d.std(axis=0).round(2)}")

if data_minmax is not None:
    print("\nMin-Max нормализациясы:")
    print(f"  Min: {data_minmax.min(axis=0).round(4)}")
    print(f"  Max: {data_minmax.max(axis=0).round(4)}")

if data_standard is not None:
    print("\nZ-score стандарттау:")
    print(f"  Орта: {data_standard.mean(axis=0).round(4)}")
    print(f"  Std:  {data_standard.std(axis=0).round(4)}")

In [ ]:
# Тапсырма 5.4: Robust нормализация — аномалиялы мәндерге тұрақтылық

from sklearn.preprocessing import RobustScaler

data_clean = np.array([10, 12, 11, 13, 10, 12, 11, 14, 10, 12], dtype=float)
data_outliers = np.array([10, 12, 11, 13, 10, 12, 11, 14, 10, 1000], dtype=float)

# TODO: StandardScaler арқылы екі деректер жиынын стандарттаңыз
std_clean = None
std_outliers = None

# TODO: RobustScaler арқылы екі деректер жиынын трансформациялаңыз
robust_clean = None
robust_outliers = None

print("Standard Scaler нәтижелері:")
print(f"  Таза деректер std:     {std_clean}")
print(f"  Аномалиялы деректер:   {std_outliers}")
print("\nRobust Scaler нәтижелері:")
print(f"  Таза деректер:         {robust_clean}")
print(f"  Аномалиялы деректер:   {robust_outliers}")

In [ ]:
# Тапсырма 5.5: Нормализация әдістерін визуалды салыстыру

from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler

np.random.seed(42)
raw = np.concatenate([np.random.normal(20, 5, 95), [80, 85, 90, -10, -15]]).reshape(-1, 1)

# TODO: үш скалер объектісін жасап, деректерді трансформациялаңыз
minmax_data = None
standard_data = None
robust_data = None

fig, axes = plt.subplots(2, 2, figsize=(12, 8))

axes[0, 0].hist(raw, bins=30, color='steelblue', edgecolor='white')
axes[0, 0].set_title("Бастапқы деректер")
axes[0, 0].grid(alpha=0.3)

datasets = [(minmax_data, 'Min-Max', 'coral'),
            (standard_data, 'Z-score', 'lightgreen'),
            (robust_data, 'Robust', 'violet')]

for ax, (d, title, color) in zip([axes[0, 1], axes[1, 0], axes[1, 1]], datasets):
    if d is not None:
        ax.hist(d, bins=30, color=color, edgecolor='white')
    ax.set_title(f"{title} нормализациясы")
    ax.grid(alpha=0.3)

plt.tight_layout()
plt.show()

In [ ]:
# Тапсырма 5.6: Батч нормализациясының принципі
# Жасанды нейрон желілерінде оқыту жылдамдығын арттырады

def batch_normalize(X, epsilon=1e-8):
    # TODO: X матрицасын батч нормализациялаңыз
    # Формула: (X - mean) / sqrt(var + epsilon)
    # Орта мен дисперсияны бағаналар (axis=0) бойынша есептеңіз
    mean = None
    var = None
    X_norm = None
    return X_norm

X = np.array([
    [1.0, 200.0, 0.5],
    [2.0, 250.0, 0.7],
    [3.0, 300.0, 0.3],
    [4.0, 350.0, 0.9],
])

X_normalized = batch_normalize(X)

print("Бастапқы деректер:\n", X)
print("\nБатч нормализациясынан кейін:\n", X_normalized)
if X_normalized is not None:
    print("\nБағаналар ортасы (0-ге жақын болуы тиіс):", X_normalized.mean(axis=0).round(6))
    print("Бағаналар std (1-ге жақын болуы тиіс):", X_normalized.std(axis=0).round(4))

In [ ]:
# Тапсырма 5.7: Train/Test жиындарын жеке нормализациялау
# Маңызды ереже: Test жиынына тек Train жиынының параметрлері қолданылады

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

np.random.seed(42)
X = np.random.randn(200, 4) * np.array([10, 5, 20, 1])
y = np.random.randint(0, 2, 200)

# TODO: X және y-ні 80/20 қатынасында бөліңіз (test_size=0.2)
X_train, X_test, y_train, y_test = None, None, None, None

# TODO: StandardScaler жасап, тек X_train-ге fit_transform қолданыңыз
scaler = StandardScaler()
X_train_scaled = None

# TODO: тек transform арқылы X_test-ті трансформациялаңыз (fit ЕМЕС!)
X_test_scaled = None

print("Train жиыны пішіні:", X_train.shape if X_train is not None else "TODO")
print("Test жиыны пішіні:", X_test.shape if X_test is not None else "TODO")
if X_train_scaled is not None:
    print(f"Train scaled орта: {X_train_scaled.mean(axis=0).round(4)}")
    print(f"Train scaled std:  {X_train_scaled.std(axis=0).round(4)}")

In [ ]:
# Тапсырма 5.8: L1 және L2 нормализациясы — векторлар үшін
# Мәтіндік деректерде (TF-IDF) және спарс деректерде қолданылады

from sklearn.preprocessing import normalize

X = np.array([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0],
    [7.0, 8.0, 9.0],
])

# TODO: normalize() арқылы L1 нормализациясын орындаңыз (norm='l1')
X_l1 = None

# TODO: normalize() арқылы L2 нормализациясын орындаңыз (norm='l2')
X_l2 = None

print("Бастапқы матрица:\n", X)
print("\nL1 нормализациясы:\n", X_l1)
if X_l1 is not None:
    print("Жол қосындылары (1.0 болуы тиіс):", X_l1.sum(axis=1))

print("\nL2 нормализациясы:\n", X_l2)
if X_l2 is not None:
    print("Жол нормалары (1.0 болуы тиіс):", np.linalg.norm(X_l2, axis=1))

In [ ]:
# Тапсырма 5.9: Нормализациясыз vs нормализациямен — Gradient Descent
# Нормализацияның оқыту жылдамдығына әсерін бақылаңыз

def gradient_descent(X, y, lr=0.01, n_iterations=100):
    m, n = X.shape
    theta = np.zeros(n)
    loss_history = []
    for _ in range(n_iterations):
        # TODO: болжамды есептеңіз: y_pred = X @ theta
        y_pred = None
        # TODO: қатені есептеңіз: error = y_pred - y
        error = None
        # TODO: MSE шығынын есептеңіз: loss = mean(error^2)
        loss = None
        # TODO: градиентті есептеңіз: gradient = X.T @ error / m
        gradient = None
        # TODO: параметрлерді жаңартыңыз: theta -= lr * gradient
        if y_pred is not None and gradient is not None:
            theta -= lr * gradient
            loss_history.append(loss)
    return theta, loss_history

np.random.seed(42)
X_raw = np.random.randn(200, 2) * np.array([100, 1])
y = 3 * X_raw[:, 0] + 5 * X_raw[:, 1] + np.random.randn(200)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_raw)

_, loss_raw = gradient_descent(X_raw, y, lr=0.0001, n_iterations=200)
_, loss_scaled = gradient_descent(X_scaled, y, lr=0.01, n_iterations=200)

plt.figure(figsize=(10, 4))
if loss_raw:
    plt.plot(loss_raw, 'r-', label='Нормализациясыз', alpha=0.8)
if loss_scaled:
    plt.plot(loss_scaled, 'b-', label='Нормализациямен', alpha=0.8)
plt.xlabel("Итерация")
plt.ylabel("MSE шығыны")
plt.title("Gradient Descent: нормализация әсері")
plt.legend()
plt.grid(alpha=0.3)
plt.show()

In [ ]:
# Тапсырма 5.10: Жиынтық есеп — нормализация әдістерін салыстыру
# Барлық 5 бөлімдегі білімді пайдаланып, толық алдын ала өңдеу конвейерін жасаңыз

from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler, normalize
from sklearn.pipeline import Pipeline
import pandas as pd

np.random.seed(42)
# Аномалиялы мәндері бар жасанды деректер жиыны
data = np.random.randn(200, 3) * np.array([50, 1, 200])
# Аномалиялар қосу
data[0, 0] = 5000
data[1, 2] = -9000

scalers = {
    'Min-Max': MinMaxScaler(),
    'Z-score': StandardScaler(),
    'Robust':  RobustScaler(),
}

results = {}
for name, scaler in scalers.items():
    # TODO: деректерді трансформациялап, орта мен std-ді сақтаңыз
    scaled = None
    if scaled is not None:
        results[name] = {
            'mean': scaled.mean(axis=0).round(4),
            'std': scaled.std(axis=0).round(4),
            'min': scaled.min(axis=0).round(4),
            'max': scaled.max(axis=0).round(4),
        }

print("Нормализация әдістерін салыстыру:")
print("=" * 60)
for name, stats_dict in results.items():
    print(f"\n{name}:")
    for stat, val in stats_dict.items():
        print(f"  {stat}: {val}")

print("\nQорытынды:")
print("  Min-Max: [0,1] аралығына қысады, аномалияларға сезімтал")
print("  Z-score: орта=0, std=1, нормаль таралым болжайды")
print("  Robust:  медиана мен IQR, аномалияларға тұрақты")

# Қорытынды

Осы практикалық жұмыста сіз келесі тақырыптарды меңгердіңіз:

**1-бөлім:** Векторлар мен матрицалардың негізгі операциялары, SVD ыдырату, меншікті мәндер

**2-бөлім:** L1, L2, L-inf нормалары, Евклидтік және Манхэттен қашықтықтары, косинустық ұқсастық

**3-бөлім:** Байес теоремасы, математикалық үміт, дисперсия, ковариация, Монте-Карло

**4-бөлім:** Нормаль, биномдық, Пуассон, t-, chi-квадрат таралымдары; гипотезаларды тексеру

**5-бөлім:** Min-Max, Z-score, Robust нормализациялары; train/test жиындарын дұрыс өңдеу

Бұл математикалық негіз машиналық оқытудың барлық алгоритмдерінде регрессиядан бастап терең желілерге дейін қолданылады.